export const INCREASE_QUANTITY = "CART/INCREASE_QUANTITY";
export const DECREASE_QUANTITY = "CART/DECREASE_QUANTITY";
export const ADD_TO_CART = "CART/ADD_TO_CART";
export const REMOVE_FROM_CART = "CART/REMOVE_FROM_CART";